List<Map<String, dynamic>> addedCaneList =
  [
    {
      'id': 0,
      'name': 'ガイコツまどうの杖 +1',
      'itemType': 'cane',
      'askPrice': 330,
      'sellPrice': 180,
      'description':
          '1. 鈍足化、ワープ、混乱、睡眠のうち1つの効果がランダムで発生 \n2. ガイコツまどう系モンスターからドロップ',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 30
    },
    {
      'id': 0,
      'name': 'ガイコツまどうの杖 +2',
      'itemType': 'cane',
      'askPrice': 360,
      'sellPrice': 210,
      'description':
          '1. 鈍足化、ワープ、混乱、睡眠のうち1つの効果がランダムで発生 \n2. ガイコツまどう系モンスターからドロップ',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 30
    },
    {
      'id': 0,
      'name': 'ガイコツまどうの杖 +3',
      'itemType': 'cane',
      'askPrice': 390,
      'sellPrice': 240,
      'description':
          '1. 鈍足化、ワープ、混乱、睡眠のうち1つの効果がランダムで発生 \n2. ガイコツまどう系モンスターからドロップ',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 30
    },
    {
      'id': 0,
      'name': 'ガイコツまどうの杖 +4',
      'itemType': 'cane',
      'askPrice': 420,
      'sellPrice': 270,
      'description':
          '1. 鈍足化、ワープ、混乱、睡眠のうち1つの効果がランダムで発生 \n2. ガイコツまどう系モンスターからドロップ',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 30
    },
    {
      'id': 0,
      'name': 'ガイコツまどうの杖 +5',
      'itemType': 'cane',
      'askPrice': 450,
      'sellPrice': 300,
      'description':
          '1. 鈍足化、ワープ、混乱、睡眠のうち1つの効果がランダムで発生 \n2. ガイコツまどう系モンスターからドロップ',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 30
    },
    {
      'id': 0,
      'name': 'ガイコツまどうの杖 +6',
      'itemType': 'cane',
      'askPrice': 480,
      'sellPrice': 330,
      'description':
          '1. 鈍足化、ワープ、混乱、睡眠のうち1つの効果がランダムで発生 \n2. ガイコツまどう系モンスターからドロップ',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 30
    },
    {
      'id': 0,
      'name': 'ガイコツまどうの杖 +7',
      'itemType': 'cane',
      'askPrice': 510,
      'sellPrice': 360,
      'description':
          '1. 鈍足化、ワープ、混乱、睡眠のうち1つの効果がランダムで発生 \n2. ガイコツまどう系モンスターからドロップ',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 30
    },
    {
      'id': 0,
      'name': '一時しのぎの杖 +1',
      'itemType': 'cane',
      'askPrice': 550,
      'sellPrice': 300,
      'description': '1. モンスターを階段上にワープさせ、金縛り状態にさせる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '一時しのぎの杖 +2',
      'itemType': 'cane',
      'askPrice': 600,
      'sellPrice': 350,
      'description': '1. モンスターを階段上にワープさせ、金縛り状態にさせる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '一時しのぎの杖 +3',
      'itemType': 'cane',
      'askPrice': 650,
      'sellPrice': 400,
      'description': '1. モンスターを階段上にワープさせ、金縛り状態にさせる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '一時しのぎの杖 +4',
      'itemType': 'cane',
      'askPrice': 700,
      'sellPrice': 450,
      'description': '1. モンスターを階段上にワープさせ、金縛り状態にさせる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '一時しのぎの杖 +5',
      'itemType': 'cane',
      'askPrice': 750,
      'sellPrice': 500,
      'description': '1. モンスターを階段上にワープさせ、金縛り状態にさせる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '一時しのぎの杖 +6',
      'itemType': 'cane',
      'askPrice': 800,
      'sellPrice': 550,
      'description': '1. モンスターを階段上にワープさせ、金縛り状態にさせる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '一時しのぎの杖 +7',
      'itemType': 'cane',
      'askPrice': 850,
      'sellPrice': 600,
      'description': '1. モンスターを階段上にワープさせ、金縛り状態にさせる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'しあわせの杖 +1',
      'itemType': 'cane',
      'askPrice': 550,
      'sellPrice': 300,
      'description': '1. モンスターのレベルを1上昇 \n2. 自分に当てたときは経験値が500上昇',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'しあわせの杖 +2',
      'itemType': 'cane',
      'askPrice': 600,
      'sellPrice': 350,
      'description': '1. モンスターのレベルを1上昇 \n2. 自分に当てたときは経験値が500上昇',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'しあわせの杖 +3',
      'itemType': 'cane',
      'askPrice': 650,
      'sellPrice': 400,
      'description': '1. モンスターのレベルを1上昇 \n2. 自分に当てたときは経験値が500上昇',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'しあわせの杖 +4',
      'itemType': 'cane',
      'askPrice': 700,
      'sellPrice': 450,
      'description': '1. モンスターのレベルを1上昇 \n2. 自分に当てたときは経験値が500上昇',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'しあわせの杖 +5',
      'itemType': 'cane',
      'askPrice': 750,
      'sellPrice': 500,
      'description': '1. モンスターのレベルを1上昇 \n2. 自分に当てたときは経験値が500上昇',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'しあわせの杖 +6',
      'itemType': 'cane',
      'askPrice': 800,
      'sellPrice': 550,
      'description': '1. モンスターのレベルを1上昇 \n2. 自分に当てたときは経験値が500上昇',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'しあわせの杖 +7',
      'itemType': 'cane',
      'askPrice': 850,
      'sellPrice': 600,
      'description': '1. モンスターのレベルを1上昇 \n2. 自分に当てたときは経験値が500上昇',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'ふきとばしの杖 +1',
      'itemType': 'cane',
      'askPrice': 550,
      'sellPrice': 300,
      'description': '1. モンスターを吹き飛ばし、10ダメージ与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'ふきとばしの杖 +2',
      'itemType': 'cane',
      'askPrice': 600,
      'sellPrice': 350,
      'description': '1. モンスターを吹き飛ばし、10ダメージ与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'ふきとばしの杖 +3',
      'itemType': 'cane',
      'askPrice': 650,
      'sellPrice': 400,
      'description': '1. モンスターを吹き飛ばし、10ダメージ与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'ふきとばしの杖 +4',
      'itemType': 'cane',
      'askPrice': 700,
      'sellPrice': 450,
      'description': '1. モンスターを吹き飛ばし、10ダメージ与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'ふきとばしの杖 +5',
      'itemType': 'cane',
      'askPrice': 750,
      'sellPrice': 500,
      'description': '1. モンスターを吹き飛ばし、10ダメージ与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'ふきとばしの杖 +6',
      'itemType': 'cane',
      'askPrice': 800,
      'sellPrice': 550,
      'description': '1. モンスターを吹き飛ばし、10ダメージ与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': 'ふきとばしの杖 +7',
      'itemType': 'cane',
      'askPrice': 850,
      'sellPrice': 600,
      'description': '1. モンスターを吹き飛ばし、10ダメージ与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '不幸の杖 +1',
      'itemType': 'cane',
      'askPrice': 550,
      'sellPrice': 300,
      'description': '1. モンスターのレベルを1減少 \n2. 自分に当てたときはレベルが1減少',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '不幸の杖 +2',
      'itemType': 'cane',
      'askPrice': 600,
      'sellPrice': 350,
      'description': '1. モンスターのレベルを1減少 \n2. 自分に当てたときはレベルが1減少',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '不幸の杖 +3',
      'itemType': 'cane',
      'askPrice': 650,
      'sellPrice': 400,
      'description': '1. モンスターのレベルを1減少 \n2. 自分に当てたときはレベルが1減少',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '不幸の杖 +4',
      'itemType': 'cane',
      'askPrice': 700,
      'sellPrice': 450,
      'description': '1. モンスターのレベルを1減少 \n2. 自分に当てたときはレベルが1減少',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '不幸の杖 +5',
      'itemType': 'cane',
      'askPrice': 750,
      'sellPrice': 500,
      'description': '1. モンスターのレベルを1減少 \n2. 自分に当てたときはレベルが1減少',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '不幸の杖 +6',
      'itemType': 'cane',
      'askPrice': 800,
      'sellPrice': 550,
      'description': '1. モンスターのレベルを1減少 \n2. 自分に当てたときはレベルが1減少',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '不幸の杖 +7',
      'itemType': 'cane',
      'askPrice': 850,
      'sellPrice': 600,
      'description': '1. モンスターのレベルを1減少 \n2. 自分に当てたときはレベルが1減少',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 50
    },
    {
      'id': 0,
      'name': '場所替えの杖 +1',
      'itemType': 'cane',
      'askPrice': 770,
      'sellPrice': 420,
      'description': '1. モンスターとシレンの場所を入れ替える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 70
    },
    {
      'id': 0,
      'name': '場所替えの杖 +2',
      'itemType': 'cane',
      'askPrice': 840,
      'sellPrice': 490,
      'description': '1. モンスターとシレンの場所を入れ替える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 70
    },
    {
      'id': 0,
      'name': '場所替えの杖 +3',
      'itemType': 'cane',
      'askPrice': 910,
      'sellPrice': 560,
      'description': '1. モンスターとシレンの場所を入れ替える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 70
    },
    {
      'id': 0,
      'name': '場所替えの杖 +4',
      'itemType': 'cane',
      'askPrice': 980,
      'sellPrice': 630,
      'description': '1. モンスターとシレンの場所を入れ替える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 70
    },
    {
      'id': 0,
      'name': '場所替えの杖 +5',
      'itemType': 'cane',
      'askPrice': 1050,
      'sellPrice': 700,
      'description': '1. モンスターとシレンの場所を入れ替える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 70
    },
    {
      'id': 0,
      'name': '場所替えの杖 +6',
      'itemType': 'cane',
      'askPrice': 1120,
      'sellPrice': 770,
      'description': '1. モンスターとシレンの場所を入れ替える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 70
    },
    {
      'id': 0,
      'name': '場所替えの杖 +7',
      'itemType': 'cane',
      'askPrice': 1190,
      'sellPrice': 840,
      'description': '1. モンスターとシレンの場所を入れ替える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 70
    },
    {
      'id': 0,
      'name': '痛み分けの杖 +1',
      'itemType': 'cane',
      'askPrice': 1100,
      'sellPrice': 600,
      'description': '1. モンスターに振ると、自分の受けたダメージを与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '痛み分けの杖 +2',
      'itemType': 'cane',
      'askPrice': 1200,
      'sellPrice': 700,
      'description': '1. モンスターに振ると、自分の受けたダメージを与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '痛み分けの杖 +3',
      'itemType': 'cane',
      'askPrice': 1300,
      'sellPrice': 800,
      'description': '1. モンスターに振ると、自分の受けたダメージを与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '痛み分けの杖 +4',
      'itemType': 'cane',
      'askPrice': 1400,
      'sellPrice': 900,
      'description': '1. モンスターに振ると、自分の受けたダメージを与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '痛み分けの杖 +5',
      'itemType': 'cane',
      'askPrice': 1500,
      'sellPrice': 1000,
      'description': '1. モンスターに振ると、自分の受けたダメージを与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '痛み分けの杖 +6',
      'itemType': 'cane',
      'askPrice': 1600,
      'sellPrice': 1100,
      'description': '1. モンスターに振ると、自分の受けたダメージを与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '痛み分けの杖 +7',
      'itemType': 'cane',
      'askPrice': 1700,
      'sellPrice': 1200,
      'description': '1. モンスターに振ると、自分の受けたダメージを与える',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': 'かなしばりの杖 +1',
      'itemType': 'cane',
      'askPrice': 1100,
      'sellPrice': 600,
      'description': '1. モンスターを金縛り状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': 'かなしばりの杖 +2',
      'itemType': 'cane',
      'askPrice': 1200,
      'sellPrice': 700,
      'description': '1. モンスターを金縛り状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': 'かなしばりの杖 +3',
      'itemType': 'cane',
      'askPrice': 1300,
      'sellPrice': 800,
      'description': '1. モンスターを金縛り状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': 'かなしばりの杖 +4',
      'itemType': 'cane',
      'askPrice': 1400,
      'sellPrice': 900,
      'description': '1. モンスターを金縛り状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': 'かなしばりの杖 +5',
      'itemType': 'cane',
      'askPrice': 1500,
      'sellPrice': 1000,
      'description': '1. モンスターを金縛り状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': 'かなしばりの杖 +6',
      'itemType': 'cane',
      'askPrice': 1600,
      'sellPrice': 1100,
      'description': '1. モンスターを金縛り状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': 'かなしばりの杖 +7',
      'itemType': 'cane',
      'askPrice': 1700,
      'sellPrice': 1200,
      'description': '1. モンスターを金縛り状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '封印の杖 +1',
      'itemType': 'cane',
      'askPrice': 1100,
      'sellPrice': 600,
      'description': '1. モンスターの特殊能力を使用不可にする \n2. 自分に当てた場合，くちなし状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '封印の杖 +2',
      'itemType': 'cane',
      'askPrice': 1200,
      'sellPrice': 700,
      'description': '1. モンスターの特殊能力を使用不可にする \n2. 自分に当てた場合，くちなし状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '封印の杖 +3',
      'itemType': 'cane',
      'askPrice': 1300,
      'sellPrice': 800,
      'description': '1. モンスターの特殊能力を使用不可にする \n2. 自分に当てた場合，くちなし状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '封印の杖 +4',
      'itemType': 'cane',
      'askPrice': 1400,
      'sellPrice': 900,
      'description': '1. モンスターの特殊能力を使用不可にする \n2. 自分に当てた場合，くちなし状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '封印の杖 +5',
      'itemType': 'cane',
      'askPrice': 1500,
      'sellPrice': 1000,
      'description': '1. モンスターの特殊能力を使用不可にする \n2. 自分に当てた場合，くちなし状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '封印の杖 +6',
      'itemType': 'cane',
      'askPrice': 1600,
      'sellPrice': 1100,
      'description': '1. モンスターの特殊能力を使用不可にする \n2. 自分に当てた場合，くちなし状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '封印の杖 +7',
      'itemType': 'cane',
      'askPrice': 1700,
      'sellPrice': 1200,
      'description': '1. モンスターの特殊能力を使用不可にする \n2. 自分に当てた場合，くちなし状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '身代わりの杖 +1',
      'itemType': 'cane',
      'askPrice': 1100,
      'sellPrice': 600,
      'description': '1. モンスターを身代わり状態及び混乱状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '身代わりの杖 +2',
      'itemType': 'cane',
      'askPrice': 1200,
      'sellPrice': 700,
      'description': '1. モンスターを身代わり状態及び混乱状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '身代わりの杖 +3',
      'itemType': 'cane',
      'askPrice': 1300,
      'sellPrice': 800,
      'description': '1. モンスターを身代わり状態及び混乱状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '身代わりの杖 +4',
      'itemType': 'cane',
      'askPrice': 1400,
      'sellPrice': 900,
      'description': '1. モンスターを身代わり状態及び混乱状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '身代わりの杖 +5',
      'itemType': 'cane',
      'askPrice': 1500,
      'sellPrice': 1000,
      'description': '1. モンスターを身代わり状態及び混乱状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '身代わりの杖 +6',
      'itemType': 'cane',
      'askPrice': 1600,
      'sellPrice': 1100,
      'description': '1. モンスターを身代わり状態及び混乱状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': '身代わりの杖 +7',
      'itemType': 'cane',
      'askPrice': 1700,
      'sellPrice': 1200,
      'description': '1. モンスターを身代わり状態及び混乱状態にする',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 100
    },
    {
      'id': 0,
      'name': 'ブフーの杖 +1',
      'itemType': 'cane',
      'askPrice': 2200,
      'sellPrice': 1200,
      'description': '1. モンスターを肉に変える \n2. 自分に当てた場合，おにぎり状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 200
    },
    {
      'id': 0,
      'name': 'ブフーの杖 +2',
      'itemType': 'cane',
      'askPrice': 2400,
      'sellPrice': 1400,
      'description': '1. モンスターを肉に変える \n2. 自分に当てた場合，おにぎり状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 200
    },
    {
      'id': 0,
      'name': 'ブフーの杖 +3',
      'itemType': 'cane',
      'askPrice': 2600,
      'sellPrice': 1600,
      'description': '1. モンスターを肉に変える \n2. 自分に当てた場合，おにぎり状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 200
    },
    {
      'id': 0,
      'name': 'ブフーの杖 +4',
      'itemType': 'cane',
      'askPrice': 2800,
      'sellPrice': 1800,
      'description': '1. モンスターを肉に変える \n2. 自分に当てた場合，おにぎり状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 200
    },
    {
      'id': 0,
      'name': 'ブフーの杖 +5',
      'itemType': 'cane',
      'askPrice': 3000,
      'sellPrice': 2000,
      'description': '1. モンスターを肉に変える \n2. 自分に当てた場合，おにぎり状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 200
    },
    {
      'id': 0,
      'name': 'ブフーの杖 +6',
      'itemType': 'cane',
      'askPrice': 3200,
      'sellPrice': 2200,
      'description': '1. モンスターを肉に変える \n2. 自分に当てた場合，おにぎり状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 200
    },
    {
      'id': 0,
      'name': 'ブフーの杖 +7',
      'itemType': 'cane',
      'askPrice': 3400,
      'sellPrice': 2400,
      'description': '1. モンスターを肉に変える \n2. 自分に当てた場合，おにぎり状態になる',
      'attackNumber': null,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 200
    }
];
