List<Map<String, dynamic>> addedCrockList = [
  {
    'id': 0,
    'name': 'やりすごしの壷 +1',
    'itemType': 'crock',
    'askPrice': 1000,
    'sellPrice': 400,
    'description': '1. \n2.ターンの間やりすごし状態になる \n2. モンスターに投げた場合，閉じ込めることができる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': 'やりすごしの壷 +2',
    'itemType': 'crock',
    'askPrice': 1000,
    'sellPrice': 400,
    'description': '1. \n2.ターンの間やりすごし状態になる \n2. モンスターに投げた場合，閉じ込めることができる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': 'やりすごしの壷 +3',
    'itemType': 'crock',
    'askPrice': 1000,
    'sellPrice': 400,
    'description': '1. \n2.ターンの間やりすごし状態になる \n2. モンスターに投げた場合，閉じ込めることができる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': 'やりすごしの壷 +4',
    'itemType': 'crock',
    'askPrice': 1000,
    'sellPrice': 400,
    'description': '1. \n2.ターンの間やりすごし状態になる \n2. モンスターに投げた場合，閉じ込めることができる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': 'やりすごしの壷 +5',
    'itemType': 'crock',
    'askPrice': 1000,
    'sellPrice': 400,
    'description': '1. \n2.ターンの間やりすごし状態になる \n2. モンスターに投げた場合，閉じ込めることができる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': 'やりすごしの壷 +6',
    'itemType': 'crock',
    'askPrice': 1000,
    'sellPrice': 400,
    'description': '1. \n2.ターンの間やりすごし状態になる \n2. モンスターに投げた場合，閉じ込めることができる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '弱化の壷 +1',
    'itemType': 'crock',
    'askPrice': 1100,
    'sellPrice': 300,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が3減少する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '弱化の壷 +2',
    'itemType': 'crock',
    'askPrice': 1200,
    'sellPrice': 400,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が3減少する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '弱化の壷 +3',
    'itemType': 'crock',
    'askPrice': 1300,
    'sellPrice': 500,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が3減少する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '弱化の壷 +4',
    'itemType': 'crock',
    'askPrice': 1400,
    'sellPrice': 600,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が3減少する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '弱化の壷 +5',
    'itemType': 'crock',
    'askPrice': 1500,
    'sellPrice': 700,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が3減少する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '弱化の壷 +6',
    'itemType': 'crock',
    'askPrice': 1600,
    'sellPrice': 800,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が3減少する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '識別の壷 +1',
    'itemType': 'crock',
    'askPrice': 1100,
    'sellPrice': 600,
    'description': '1. アイテムを入れると，識別状態になる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '識別の壷 +2',
    'itemType': 'crock',
    'askPrice': 1200,
    'sellPrice': 700,
    'description': '1. アイテムを入れると，識別状態になる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '識別の壷 +3',
    'itemType': 'crock',
    'askPrice': 1300,
    'sellPrice': 800,
    'description': '1. アイテムを入れると，識別状態になる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '識別の壷 +4',
    'itemType': 'crock',
    'askPrice': 1400,
    'sellPrice': 900,
    'description': '1. アイテムを入れると，識別状態になる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '識別の壷 +5',
    'itemType': 'crock',
    'askPrice': 1500,
    'sellPrice': 1000,
    'description': '1. アイテムを入れると，識別状態になる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '識別の壷 +6',
    'itemType': 'crock',
    'askPrice': 1600,
    'sellPrice': 1100,
    'description': '1. アイテムを入れると，識別状態になる',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '変化の壷 +1',
    'itemType': 'crock',
    'askPrice': 1100,
    'sellPrice': 600,
    'description': '1. アイテムを入れると，別のアイテムに変化',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '変化の壷 +2',
    'itemType': 'crock',
    'askPrice': 1200,
    'sellPrice': 700,
    'description': '1. アイテムを入れると，別のアイテムに変化',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '変化の壷 +3',
    'itemType': 'crock',
    'askPrice': 1300,
    'sellPrice': 800,
    'description': '1. アイテムを入れると，別のアイテムに変化',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '変化の壷 +4',
    'itemType': 'crock',
    'askPrice': 1400,
    'sellPrice': 900,
    'description': '1. アイテムを入れると，別のアイテムに変化',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '変化の壷 +5',
    'itemType': 'crock',
    'askPrice': 1500,
    'sellPrice': 1000,
    'description': '1. アイテムを入れると，別のアイテムに変化',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '変化の壷 +6',
    'itemType': 'crock',
    'askPrice': 1600,
    'sellPrice': 1100,
    'description': '1. アイテムを入れると，別のアイテムに変化',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 100
  },
  {
    'id': 0,
    'name': '背中の壷 +1',
    'itemType': 'crock',
    'askPrice': 1650,
    'sellPrice': 850,
    'description': '1. 押すと、目潰し状態、惑わし状態、混乱状態、ちから及びHPを回復',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 150
  },
  {
    'id': 0,
    'name': '背中の壷 +2',
    'itemType': 'crock',
    'askPrice': 1800,
    'sellPrice': 1000,
    'description': '1. 押すと、目潰し状態、惑わし状態、混乱状態、ちから及びHPを回復',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 150
  },
  {
    'id': 0,
    'name': '背中の壷 +3',
    'itemType': 'crock',
    'askPrice': 1950,
    'sellPrice': 1150,
    'description': '1. 押すと、目潰し状態、惑わし状態、混乱状態、ちから及びHPを回復',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 150
  },
  {
    'id': 0,
    'name': '背中の壷 +4',
    'itemType': 'crock',
    'askPrice': 2100,
    'sellPrice': 1300,
    'description': '1. 押すと、目潰し状態、惑わし状態、混乱状態、ちから及びHPを回復',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 150
  },
  {
    'id': 0,
    'name': '背中の壷 +5',
    'itemType': 'crock',
    'askPrice': 2250,
    'sellPrice': 1450,
    'description': '1. 押すと、目潰し状態、惑わし状態、混乱状態、ちから及びHPを回復',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 150
  },
  {
    'id': 0,
    'name': '背中の壷 +6',
    'itemType': 'crock',
    'askPrice': 2400,
    'sellPrice': 1600,
    'description': '1. 押すと、目潰し状態、惑わし状態、混乱状態、ちから及びHPを回復',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 150
  },
  {
    'id': 0,
    'name': '保存の壷 +1',
    'itemType': 'crock',
    'askPrice': 1600,
    'sellPrice': 600,
    'description': '1. アイテムを入れると，自由に使用できる ( アイテム所持数の増加 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '保存の壷 +2',
    'itemType': 'crock',
    'askPrice': 1600,
    'sellPrice': 600,
    'description': '1. アイテムを入れると，自由に使用できる ( アイテム所持数の増加 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '保存の壷 +3',
    'itemType': 'crock',
    'askPrice': 1600,
    'sellPrice': 600,
    'description': '1. アイテムを入れると，自由に使用できる ( アイテム所持数の増加 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '保存の壷 +4',
    'itemType': 'crock',
    'askPrice': 1600,
    'sellPrice': 600,
    'description': '1. アイテムを入れると，自由に使用できる ( アイテム所持数の増加 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '保存の壷 +5',
    'itemType': 'crock',
    'askPrice': 1600,
    'sellPrice': 600,
    'description': '1. アイテムを入れると，自由に使用できる ( アイテム所持数の増加 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '保存の壷 +6',
    'itemType': 'crock',
    'askPrice': 1600,
    'sellPrice': 600,
    'description': '1. アイテムを入れると，自由に使用できる ( アイテム所持数の増加 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': 'トドの壷 +1',
    'itemType': 'crock',
    'askPrice': 1760,
    'sellPrice': 760,
    'description':
        '1. 押すと，前方のアイテムを壺に入れられる ( 壷は不可，店のアイテムを盗める ) \n2. 投げて割ると，回数分のぬすっトドが混乱状態で発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 160
  },
  {
    'id': 0,
    'name': 'トドの壷 +2',
    'itemType': 'crock',
    'askPrice': 1920,
    'sellPrice': 920,
    'description':
        '1. 押すと，前方のアイテムを壺に入れられる ( 壷は不可，店のアイテムを盗める ) \n2. 投げて割ると，回数分のぬすっトドが混乱状態で発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 160
  },
  {
    'id': 0,
    'name': 'トドの壷 +3',
    'itemType': 'crock',
    'askPrice': 2080,
    'sellPrice': 1080,
    'description':
        '1. 押すと，前方のアイテムを壺に入れられる ( 壷は不可，店のアイテムを盗める ) \n2. 投げて割ると，回数分のぬすっトドが混乱状態で発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 160
  },
  {
    'id': 0,
    'name': 'トドの壷 +4',
    'itemType': 'crock',
    'askPrice': 2240,
    'sellPrice': 1240,
    'description':
        '1. 押すと，前方のアイテムを壺に入れられる ( 壷は不可，店のアイテムを盗める ) \n2. 投げて割ると，回数分のぬすっトドが混乱状態で発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 160
  },
  {
    'id': 0,
    'name': 'トドの壷 +5',
    'itemType': 'crock',
    'askPrice': 2400,
    'sellPrice': 1400,
    'description':
        '1. 押すと，前方のアイテムを壺に入れられる ( 壷は不可，店のアイテムを盗める ) \n2. 投げて割ると，回数分のぬすっトドが混乱状態で発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 160
  },
  {
    'id': 0,
    'name': 'トドの壷 +6',
    'itemType': 'crock',
    'askPrice': 2560,
    'sellPrice': 1560,
    'description':
        '1. 押すと，前方のアイテムを壺に入れられる ( 壷は不可，店のアイテムを盗める ) \n2. 投げて割ると，回数分のぬすっトドが混乱状態で発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 160
  },
  {
    'id': 0,
    'name': '魔物のるつぼ +1',
    'itemType': 'crock',
    'askPrice': 2200,
    'sellPrice': 500,
    'description': '1, 押すと，周囲にフロアのモンスターが回数分発生 ( 割ると混乱状態で発生 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 200
  },
  {
    'id': 0,
    'name': '魔物のるつぼ +2',
    'itemType': 'crock',
    'askPrice': 2400,
    'sellPrice': 700,
    'description': '1, 押すと，周囲にフロアのモンスターが回数分発生 ( 割ると混乱状態で発生 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 200
  },
  {
    'id': 0,
    'name': '魔物のるつぼ +3',
    'itemType': 'crock',
    'askPrice': 2600,
    'sellPrice': 900,
    'description': '1, 押すと，周囲にフロアのモンスターが回数分発生 ( 割ると混乱状態で発生 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 200
  },
  {
    'id': 0,
    'name': '魔物のるつぼ +4',
    'itemType': 'crock',
    'askPrice': 2800,
    'sellPrice': 1100,
    'description': '1, 押すと，周囲にフロアのモンスターが回数分発生 ( 割ると混乱状態で発生 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 200
  },
  {
    'id': 0,
    'name': '魔物のるつぼ +5',
    'itemType': 'crock',
    'askPrice': 3000,
    'sellPrice': 1300,
    'description': '1, 押すと，周囲にフロアのモンスターが回数分発生 ( 割ると混乱状態で発生 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 200
  },
  {
    'id': 0,
    'name': '魔物のるつぼ +6',
    'itemType': 'crock',
    'askPrice': 3200,
    'sellPrice': 1500,
    'description': '1, 押すと，周囲にフロアのモンスターが回数分発生 ( 割ると混乱状態で発生 )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 200
  },
  {
    'id': 0,
    'name': '底抜けの壷 +1',
    'itemType': 'crock',
    'askPrice': 2500,
    'sellPrice': 400,
    'description':
        '1. アイテムを入れると，入れたアイテムが消滅 \n2. 投げて割ると，落とし穴が発生 \n3. 吸い出しの巻物を使用すると，シレンの下に落とし穴が発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '底抜けの壷 +2',
    'itemType': 'crock',
    'askPrice': 2500,
    'sellPrice': 400,
    'description':
        '1. アイテムを入れると，入れたアイテムが消滅 \n2. 投げて割ると，落とし穴が発生 \n3. 吸い出しの巻物を使用すると，シレンの下に落とし穴が発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '底抜けの壷 +3',
    'itemType': 'crock',
    'askPrice': 2500,
    'sellPrice': 400,
    'description':
        '1. アイテムを入れると，入れたアイテムが消滅 \n2. 投げて割ると，落とし穴が発生 \n3. 吸い出しの巻物を使用すると，シレンの下に落とし穴が発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '底抜けの壷 +4',
    'itemType': 'crock',
    'askPrice': 2500,
    'sellPrice': 400,
    'description':
        '1. アイテムを入れると，入れたアイテムが消滅 \n2. 投げて割ると，落とし穴が発生 \n3. 吸い出しの巻物を使用すると，シレンの下に落とし穴が発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '底抜けの壷 +5',
    'itemType': 'crock',
    'askPrice': 2500,
    'sellPrice': 400,
    'description':
        '1. アイテムを入れると，入れたアイテムが消滅 \n2. 投げて割ると，落とし穴が発生 \n3. 吸い出しの巻物を使用すると，シレンの下に落とし穴が発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '底抜けの壷 +6',
    'itemType': 'crock',
    'askPrice': 2500,
    'sellPrice': 400,
    'description':
        '1. アイテムを入れると，入れたアイテムが消滅 \n2. 投げて割ると，落とし穴が発生 \n3. 吸い出しの巻物を使用すると，シレンの下に落とし穴が発生',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 0
  },
  {
    'id': 0,
    'name': '倉庫の壷 +1',
    'itemType': 'crock',
    'askPrice': 2750,
    'sellPrice': 1450,
    'description': '1. アイテムを入れると，渓谷の宿場の倉庫に送られる ( 倉庫が一杯だと下におちる )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 250
  },
  {
    'id': 0,
    'name': '倉庫の壷 +2',
    'itemType': 'crock',
    'askPrice': 3000,
    'sellPrice': 1700,
    'description': '1. アイテムを入れると，渓谷の宿場の倉庫に送られる ( 倉庫が一杯だと下におちる )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 250
  },
  {
    'id': 0,
    'name': '倉庫の壷 +3',
    'itemType': 'crock',
    'askPrice': 3250,
    'sellPrice': 1950,
    'description': '1. アイテムを入れると，渓谷の宿場の倉庫に送られる ( 倉庫が一杯だと下におちる )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 250
  },
  {
    'id': 0,
    'name': '倉庫の壷 +4',
    'itemType': 'crock',
    'askPrice': 3500,
    'sellPrice': 2200,
    'description': '1. アイテムを入れると，渓谷の宿場の倉庫に送られる ( 倉庫が一杯だと下におちる )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 250
  },
  {
    'id': 0,
    'name': '倉庫の壷 +5',
    'itemType': 'crock',
    'askPrice': 3750,
    'sellPrice': 2450,
    'description': '1. アイテムを入れると，渓谷の宿場の倉庫に送られる ( 倉庫が一杯だと下におちる )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 250
  },
  {
    'id': 0,
    'name': '倉庫の壷 +6',
    'itemType': 'crock',
    'askPrice': 4000,
    'sellPrice': 2700,
    'description': '1. アイテムを入れると，渓谷の宿場の倉庫に送られる ( 倉庫が一杯だと下におちる )',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': true,
    '_dungeonSyokujin': true,
    '_dungeonFei': true,
    'addedPrice': 250
  },
  {
    'id': 0,
    'name': '分裂の壷 +1',
    'itemType': 'crock',
    'askPrice': 3300,
    'sellPrice': 1800,
    'description': '1. アイテムを入れると，壺の中でアイテムが\n2.に増加',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 300
  },
  {
    'id': 0,
    'name': '分裂の壷 +2',
    'itemType': 'crock',
    'askPrice': 3600,
    'sellPrice': 2100,
    'description': '1. アイテムを入れると，壺の中でアイテムが\n2.に増加',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 300
  },
  {
    'id': 0,
    'name': '分裂の壷 +3',
    'itemType': 'crock',
    'askPrice': 3900,
    'sellPrice': 2400,
    'description': '1. アイテムを入れると，壺の中でアイテムが\n2.に増加',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 300
  },
  {
    'id': 0,
    'name': '分裂の壷 +4',
    'itemType': 'crock',
    'askPrice': 4200,
    'sellPrice': 2700,
    'description': '1. アイテムを入れると，壺の中でアイテムが\n2.に増加',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 300
  },
  {
    'id': 0,
    'name': '分裂の壷 +5',
    'itemType': 'crock',
    'askPrice': 4500,
    'sellPrice': 3000,
    'description': '1. アイテムを入れると，壺の中でアイテムが\n2.に増加',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 300
  },
  {
    'id': 0,
    'name': '分裂の壷 +6',
    'itemType': 'crock',
    'askPrice': 4800,
    'sellPrice': 3300,
    'description': '1. アイテムを入れると，壺の中でアイテムが\n2.に増加',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 300
  },
  {
    'id': 0,
    'name': '合成の壷 +1',
    'itemType': 'crock',
    'askPrice': 3850,
    'sellPrice': 1850,
    'description':
        '1. 剣，盾，杖，ギタンを各々合成させられる \n2. 剣盾の場合，修正値及び効果を合成 \n3. 杖の場合，修正値を合成 \n4. ギタンの場合，金額を合成',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 350
  },
  {
    'id': 0,
    'name': '合成の壷 +2',
    'itemType': 'crock',
    'askPrice': 4200,
    'sellPrice': 2200,
    'description':
        '1. 剣，盾，杖，ギタンを各々合成させられる \n2. 剣盾の場合，修正値及び効果を合成 \n3. 杖の場合，修正値を合成 \n4. ギタンの場合，金額を合成',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 350
  },
  {
    'id': 0,
    'name': '合成の壷 +3',
    'itemType': 'crock',
    'askPrice': 4550,
    'sellPrice': 2550,
    'description':
        '1. 剣，盾，杖，ギタンを各々合成させられる \n2. 剣盾の場合，修正値及び効果を合成 \n3. 杖の場合，修正値を合成 \n4. ギタンの場合，金額を合成',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 350
  },
  {
    'id': 0,
    'name': '合成の壷 +4',
    'itemType': 'crock',
    'askPrice': 4900,
    'sellPrice': 2900,
    'description':
        '1. 剣，盾，杖，ギタンを各々合成させられる \n2. 剣盾の場合，修正値及び効果を合成 \n3. 杖の場合，修正値を合成 \n4. ギタンの場合，金額を合成',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 350
  },
  {
    'id': 0,
    'name': '合成の壷 +5',
    'itemType': 'crock',
    'askPrice': 5250,
    'sellPrice': 3250,
    'description':
        '1. 剣，盾，杖，ギタンを各々合成させられる \n2. 剣盾の場合，修正値及び効果を合成 \n3. 杖の場合，修正値を合成 \n4. ギタンの場合，金額を合成',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 350
  },
  {
    'id': 0,
    'name': '合成の壷 +6',
    'itemType': 'crock',
    'askPrice': 5600,
    'sellPrice': 3600,
    'description':
        '1. 剣，盾，杖，ギタンを各々合成させられる \n2. 剣盾の場合，修正値及び効果を合成 \n3. 杖の場合，修正値を合成 \n4. ギタンの場合，金額を合成',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': true,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 350
  },
  {
    'id': 0,
    'name': 'アホくさい壷 +1',
    'itemType': 'crock',
    'askPrice': 8250,
    'sellPrice': 2250,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': 'アホくさい壷 +2',
    'itemType': 'crock',
    'askPrice': 9000,
    'sellPrice': 3000,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': 'アホくさい壷 +3',
    'itemType': 'crock',
    'askPrice': 9750,
    'sellPrice': 3750,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': 'アホくさい壷 +4',
    'itemType': 'crock',
    'askPrice': 10500,
    'sellPrice': 4500,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': 'アホくさい壷 +5',
    'itemType': 'crock',
    'askPrice': 11250,
    'sellPrice': 5250,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': 'アホくさい壷 +6',
    'itemType': 'crock',
    'askPrice': 12000,
    'sellPrice': 6000,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': 'うっぷんばらしの壷 +1',
    'itemType': 'crock',
    'askPrice': 8250,
    'sellPrice': 2250,
    'description': '1. 投げて割ると，爆発属性が発生する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': 'うっぷんばらしの壷 +2',
    'itemType': 'crock',
    'askPrice': 9000,
    'sellPrice': 3000,
    'description': '1. 投げて割ると，爆発属性が発生する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': 'うっぷんばらしの壷 +3',
    'itemType': 'crock',
    'askPrice': 9750,
    'sellPrice': 3750,
    'description': '1. 投げて割ると，爆発属性が発生する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': 'うっぷんばらしの壷 +4',
    'itemType': 'crock',
    'askPrice': 10500,
    'sellPrice': 4500,
    'description': '1. 投げて割ると，爆発属性が発生する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': 'うっぷんばらしの壷 +5',
    'itemType': 'crock',
    'askPrice': 11250,
    'sellPrice': 5250,
    'description': '1. 投げて割ると，爆発属性が発生する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': 'うっぷんばらしの壷 +6',
    'itemType': 'crock',
    'askPrice': 12000,
    'sellPrice': 6000,
    'description': '1. 投げて割ると，爆発属性が発生する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 750
  },
  {
    'id': 0,
    'name': '強化の壷 +1',
    'itemType': 'crock',
    'askPrice': 11000,
    'sellPrice': 6000,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が1増加する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': '強化の壷 +2',
    'itemType': 'crock',
    'askPrice': 12000,
    'sellPrice': 7000,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が1増加する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': '強化の壷 +3',
    'itemType': 'crock',
    'askPrice': 13000,
    'sellPrice': 8000,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が1増加する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': '強化の壷 +4',
    'itemType': 'crock',
    'askPrice': 14000,
    'sellPrice': 9000,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が1増加する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': '強化の壷 +5',
    'itemType': 'crock',
    'askPrice': 15000,
    'sellPrice': 10000,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が1増加する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': '強化の壷 +6',
    'itemType': 'crock',
    'askPrice': 16000,
    'sellPrice': 11000,
    'description': '1. 剣，盾，杖を入れると，1フロア進む毎に修正値が1増加する',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': '割れない壷 +1',
    'itemType': 'crock',
    'askPrice': 11000,
    'sellPrice': 2500,
    'description': '1. アイテムを保存できるが，吸い出しの巻物を使用しないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': '割れない壷 +2',
    'itemType': 'crock',
    'askPrice': 12000,
    'sellPrice': 3500,
    'description': '1. アイテムを保存できるが，吸い出しの巻物を使用しないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': '割れない壷 +3',
    'itemType': 'crock',
    'askPrice': 13000,
    'sellPrice': 4500,
    'description': '1. アイテムを保存できるが，吸い出しの巻物を使用しないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': '割れない壷 +4',
    'itemType': 'crock',
    'askPrice': 14000,
    'sellPrice': 5500,
    'description': '1. アイテムを保存できるが，吸い出しの巻物を使用しないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': '割れない壷 +5',
    'itemType': 'crock',
    'askPrice': 15000,
    'sellPrice': 6500,
    'description': '1. アイテムを保存できるが，吸い出しの巻物を使用しないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': '割れない壷 +6',
    'itemType': 'crock',
    'askPrice': 16000,
    'sellPrice': 7500,
    'description': '1. アイテムを保存できるが，吸い出しの巻物を使用しないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1000
  },
  {
    'id': 0,
    'name': 'ガイバラの壷 +1',
    'itemType': 'crock',
    'askPrice': 16500,
    'sellPrice': 3000,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1500
  },
  {
    'id': 0,
    'name': 'ガイバラの壷 +2',
    'itemType': 'crock',
    'askPrice': 18000,
    'sellPrice': 4500,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1500
  },
  {
    'id': 0,
    'name': 'ガイバラの壷 +3',
    'itemType': 'crock',
    'askPrice': 19500,
    'sellPrice': 6000,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1500
  },
  {
    'id': 0,
    'name': 'ガイバラの壷 +4',
    'itemType': 'crock',
    'askPrice': 21000,
    'sellPrice': 7500,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1500
  },
  {
    'id': 0,
    'name': 'ガイバラの壷 +5',
    'itemType': 'crock',
    'askPrice': 22500,
    'sellPrice': 9000,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1500
  },
  {
    'id': 0,
    'name': 'ガイバラの壷 +6',
    'itemType': 'crock',
    'askPrice': 24000,
    'sellPrice': 10500,
    'description': '1. アイテムを保存できるが，割らないと取り出せない',
    'attackNumber': null,
    'defenseNumber': null,
    '_dungeonTableMountain': false,
    '_dungeonKakejikuUra': false,
    '_dungeonSyokujin': false,
    '_dungeonFei': true,
    'addedPrice': 1500
  }
];
