List<Map<String, dynamic>> addedWeaponList =
  [
    {
      'id': 0,
      'name': 'つるはし -1',
      'itemType': 'sword',
      'askPrice': 233,
      'sellPrice': 93,
      'description': 'ダンジョンの壁を掘れる',
      'attackNumber': 0,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 7
    },
    {
      'id': 0,
      'name': 'つるはし +1',
      'itemType': 'sword',
      'askPrice': 247,
      'sellPrice': 107,
      'description': 'ダンジョンの壁を掘れる',
      'attackNumber': 2,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 7
    },
    {
      'id': 0,
      'name': 'つるはし +2',
      'itemType': 'sword',
      'askPrice': 254,
      'sellPrice': 114,
      'description': 'ダンジョンの壁を掘れる',
      'attackNumber': 3,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 7
    },
    {
      'id': 0,
      'name': 'つるはし +3',
      'itemType': 'sword',
      'askPrice': 261,
      'sellPrice': 121,
      'description': 'ダンジョンの壁を掘れる',
      'attackNumber': 4,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 7
    },
    {
      'id': 0,
      'name': 'こわれないつるはし -1',
      'itemType': 'sword',
      'askPrice': 233,
      'sellPrice': 93,
      'description': 'ダンジョンの壁を掘れる',
      'attackNumber': 0,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 7
    },
    {
      'id': 0,
      'name': 'こわれないつるはし +1',
      'itemType': 'sword',
      'askPrice': 247,
      'sellPrice': 107,
      'description': 'ダンジョンの壁を掘れる',
      'attackNumber': 2,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 7
    },
    {
      'id': 0,
      'name': 'こわれないつるはし +2',
      'itemType': 'sword',
      'askPrice': 254,
      'sellPrice': 114,
      'description': 'ダンジョンの壁を掘れる',
      'attackNumber': 3,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 7
    },
    {
      'id': 0,
      'name': 'こわれないつるはし +3',
      'itemType': 'sword',
      'askPrice': 261,
      'sellPrice': 121,
      'description': 'ダンジョンの壁を掘れる',
      'attackNumber': 4,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 7
    },
    {
      'id': 0,
      'name': 'こん棒 -1',
      'itemType': 'sword',
      'askPrice': 232,
      'sellPrice': 72,
      'description': 'なし',
      'attackNumber': 1,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 8
    },
    {
      'id': 0,
      'name': 'こん棒 +1',
      'itemType': 'sword',
      'askPrice': 248,
      'sellPrice': 88,
      'description': 'なし',
      'attackNumber': 3,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 8
    },
    {
      'id': 0,
      'name': 'こん棒 +2',
      'itemType': 'sword',
      'askPrice': 256,
      'sellPrice': 96,
      'description': 'なし',
      'attackNumber': 4,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 8
    },
    {
      'id': 0,
      'name': 'こん棒 +3',
      'itemType': 'sword',
      'askPrice': 264,
      'sellPrice': 104,
      'description': 'なし',
      'attackNumber': 5,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 8
    },
    {
      'id': 0,
      'name': '必中の剣 -1',
      'itemType': 'sword',
      'askPrice': 9525,
      'sellPrice': 4525,
      'description': '攻撃が必ず当たる',
      'attackNumber': 1,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 475
    },
    {
      'id': 0,
      'name': '必中の剣 +1',
      'itemType': 'sword',
      'askPrice': 10475,
      'sellPrice': 5475,
      'description': '攻撃が必ず当たる',
      'attackNumber': 3,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 475
    },
    {
      'id': 0,
      'name': '必中の剣 +2',
      'itemType': 'sword',
      'askPrice': 10950,
      'sellPrice': 5950,
      'description': '攻撃が必ず当たる',
      'attackNumber': 4,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 475
    },
    {
      'id': 0,
      'name': '必中の剣 +3',
      'itemType': 'sword',
      'askPrice': 11425,
      'sellPrice': 6425,
      'description': '攻撃が必ず当たる',
      'attackNumber': 5,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 475
    },
    {
      'id': 0,
      'name': '妖刀かまいたち -1',
      'itemType': 'sword',
      'askPrice': 4830,
      'sellPrice': 1830,
      'description': '前方3方向に攻撃可能',
      'attackNumber': 2,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 170
    },
    {
      'id': 0,
      'name': '妖刀かまいたち +1',
      'itemType': 'sword',
      'askPrice': 5170,
      'sellPrice': 2170,
      'description': '前方3方向に攻撃可能',
      'attackNumber': 4,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 170
    },
    {
      'id': 0,
      'name': '妖刀かまいたち +2',
      'itemType': 'sword',
      'askPrice': 5340,
      'sellPrice': 2340,
      'description': '前方3方向に攻撃可能',
      'attackNumber': 5,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 170
    },
    {
      'id': 0,
      'name': '妖刀かまいたち +3',
      'itemType': 'sword',
      'askPrice': 5510,
      'sellPrice': 2510,
      'description': '前方3方向に攻撃可能',
      'attackNumber': 6,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 170
    },
    {
      'id': 0,
      'name': '長巻 -1',
      'itemType': 'sword',
      'askPrice': 480,
      'sellPrice': 180,
      'description': 'なし',
      'attackNumber': 3,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 20
    },
    {
      'id': 0,
      'name': '長巻 +1',
      'itemType': 'sword',
      'askPrice': 520,
      'sellPrice': 220,
      'description': 'なし',
      'attackNumber': 5,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 20
    },
    {
      'id': 0,
      'name': '長巻 +2',
      'itemType': 'sword',
      'askPrice': 540,
      'sellPrice': 240,
      'description': 'なし',
      'attackNumber': 6,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 20
    },
    {
      'id': 0,
      'name': '長巻 +3',
      'itemType': 'sword',
      'askPrice': 560,
      'sellPrice': 260,
      'description': 'なし',
      'attackNumber': 7,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 20
    },
    {
      'id': 0,
      'name': '成仏の鎌 -1',
      'itemType': 'sword',
      'askPrice': 1925,
      'sellPrice': 825,
      'description': 'アンデッド系モンスター特攻',
      'attackNumber': 3,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 75
    },
    {
      'id': 0,
      'name': '成仏の鎌 +1',
      'itemType': 'sword',
      'askPrice': 2075,
      'sellPrice': 975,
      'description': 'アンデッド系モンスター特攻',
      'attackNumber': 5,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 75
    },
    {
      'id': 0,
      'name': '成仏の鎌 +2',
      'itemType': 'sword',
      'askPrice': 2150,
      'sellPrice': 1050,
      'description': 'アンデッド系モンスター特攻',
      'attackNumber': 6,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 75
    },
    {
      'id': 0,
      'name': '成仏の鎌 +3',
      'itemType': 'sword',
      'askPrice': 2225,
      'sellPrice': 1125,
      'description': 'アンデッド系モンスター特攻',
      'attackNumber': 7,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 75
    },
    {
      'id': 0,
      'name': 'ミノタウロスの斧 -1',
      'itemType': 'sword',
      'askPrice': 5800,
      'sellPrice': 2200,
      'description': '稀に会心の一撃が発生',
      'attackNumber': 3,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 200
    },
    {
      'id': 0,
      'name': 'ミノタウロスの斧 +1',
      'itemType': 'sword',
      'askPrice': 6200,
      'sellPrice': 2600,
      'description': '稀に会心の一撃が発生',
      'attackNumber': 5,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 200
    },
    {
      'id': 0,
      'name': 'ミノタウロスの斧 +2',
      'itemType': 'sword',
      'askPrice': 6400,
      'sellPrice': 2800,
      'description': '稀に会心の一撃が発生',
      'attackNumber': 6,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 200
    },
    {
      'id': 0,
      'name': 'ミノタウロスの斧 +3',
      'itemType': 'sword',
      'askPrice': 6600,
      'sellPrice': 3000,
      'description': '稀に会心の一撃が発生',
      'attackNumber': 7,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 200
    },
    {
      'id': 0,
      'name': 'ドレインバスター -1',
      'itemType': 'sword',
      'askPrice': 3840,
      'sellPrice': 1640,
      'description': 'ドレイン系モンスターに特攻',
      'attackNumber': 4,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 160
    },
    {
      'id': 0,
      'name': 'ドレインバスター +1',
      'itemType': 'sword',
      'askPrice': 4160,
      'sellPrice': 1960,
      'description': 'ドレイン系モンスターに特攻',
      'attackNumber': 6,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 160
    },
    {
      'id': 0,
      'name': 'ドレインバスター +2',
      'itemType': 'sword',
      'askPrice': 4320,
      'sellPrice': 2120,
      'description': 'ドレイン系モンスターに特攻',
      'attackNumber': 7,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 160
    },
    {
      'id': 0,
      'name': 'ドレインバスター +3',
      'itemType': 'sword',
      'askPrice': 4480,
      'sellPrice': 2280,
      'description': 'ドレイン系モンスターに特攻',
      'attackNumber': 8,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 160
    },
    {
      'id': 0,
      'name': '1ツ目殺し -1',
      'itemType': 'sword',
      'askPrice': 3475,
      'sellPrice': 1375,
      'description': '1ツ目系モンスターに特攻',
      'attackNumber': 4,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 125
    },
    {
      'id': 0,
      'name': '1ツ目殺し +1',
      'itemType': 'sword',
      'askPrice': 3725,
      'sellPrice': 1625,
      'description': '1ツ目系モンスターに特攻',
      'attackNumber': 6,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 125
    },
    {
      'id': 0,
      'name': '1ツ目殺し +2',
      'itemType': 'sword',
      'askPrice': 3850,
      'sellPrice': 1750,
      'description': '1ツ目系モンスターに特攻',
      'attackNumber': 7,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 125
    },
    {
      'id': 0,
      'name': '1ツ目殺し +3',
      'itemType': 'sword',
      'askPrice': 3975,
      'sellPrice': 1875,
      'description': '1ツ目系モンスターに特攻',
      'attackNumber': 8,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 125
    },
    {
      'id': 0,
      'name': 'ブフーの包丁 -1',
      'itemType': 'sword',
      'askPrice': 1945,
      'sellPrice': 745,
      'description': '1/\\n2.確率で倒したモンスターの肉アイテムが発生',
      'attackNumber': 4,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 55
    },
    {
      'id': 0,
      'name': 'ブフーの包丁 +1',
      'itemType': 'sword',
      'askPrice': 2055,
      'sellPrice': 855,
      'description': '1/\\n2.確率で倒したモンスターの肉アイテムが発生',
      'attackNumber': 6,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 55
    },
    {
      'id': 0,
      'name': 'ブフーの包丁 +2',
      'itemType': 'sword',
      'askPrice': 2110,
      'sellPrice': 910,
      'description': '1/\\n2.確率で倒したモンスターの肉アイテムが発生',
      'attackNumber': 7,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 55
    },
    {
      'id': 0,
      'name': 'ブフーの包丁 +3',
      'itemType': 'sword',
      'askPrice': 2165,
      'sellPrice': 965,
      'description': '1/\\n2.確率で倒したモンスターの肉アイテムが発生',
      'attackNumber': 8,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': true,
      '_dungeonFei': true,
      'addedPrice': 55
    },
    {
      'id': 0,
      'name': 'カタナ -1',
      'itemType': 'sword',
      'askPrice': 770,
      'sellPrice': 270,
      'description': 'なし',
      'attackNumber': 5,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 30
    },
    {
      'id': 0,
      'name': 'カタナ +1',
      'itemType': 'sword',
      'askPrice': 830,
      'sellPrice': 330,
      'description': 'なし',
      'attackNumber': 7,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 30
    },
    {
      'id': 0,
      'name': 'カタナ +2',
      'itemType': 'sword',
      'askPrice': 860,
      'sellPrice': 360,
      'description': 'なし',
      'attackNumber': 8,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 30
    },
    {
      'id': 0,
      'name': 'カタナ +3',
      'itemType': 'sword',
      'askPrice': 890,
      'sellPrice': 390,
      'description': 'なし',
      'attackNumber': 9,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 30
    },
    {
      'id': 0,
      'name': 'ドラゴンキラー -1',
      'itemType': 'sword',
      'askPrice': 3493,
      'sellPrice': 1093,
      'description': 'ドラゴン系モンスターに特攻',
      'attackNumber': 6,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 107
    },
    {
      'id': 0,
      'name': 'ドラゴンキラー +1',
      'itemType': 'sword',
      'askPrice': 3707,
      'sellPrice': 1307,
      'description': 'ドラゴン系モンスターに特攻',
      'attackNumber': 8,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 107
    },
    {
      'id': 0,
      'name': 'ドラゴンキラー +2',
      'itemType': 'sword',
      'askPrice': 3814,
      'sellPrice': 1414,
      'description': 'ドラゴン系モンスターに特攻',
      'attackNumber': 9,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 107
    },
    {
      'id': 0,
      'name': 'ドラゴンキラー +3',
      'itemType': 'sword',
      'askPrice': 3921,
      'sellPrice': 1521,
      'description': 'ドラゴン系モンスターに特攻',
      'attackNumber': 10,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 107
    },
    {
      'id': 0,
      'name': 'どうたぬき -1',
      'itemType': 'sword',
      'askPrice': 1160,
      'sellPrice': 360,
      'description': 'なし',
      'attackNumber': 7,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 40
    },
    {
      'id': 0,
      'name': 'どうたぬき +1',
      'itemType': 'sword',
      'askPrice': 1240,
      'sellPrice': 440,
      'description': 'なし',
      'attackNumber': 9,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 40
    },
    {
      'id': 0,
      'name': 'どうたぬき +2',
      'itemType': 'sword',
      'askPrice': 1280,
      'sellPrice': 480,
      'description': 'なし',
      'attackNumber': 10,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 40
    },
    {
      'id': 0,
      'name': 'どうたぬき +3',
      'itemType': 'sword',
      'askPrice': 1320,
      'sellPrice': 520,
      'description': 'なし',
      'attackNumber': 11,
      'defenseNumber': null,
      '_dungeonTableMountain': true,
      '_dungeonKakejikuUra': true,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 40
    },
    {
      'id': 0,
      'name': '剛剣マンジカブラ -1',
      'itemType': 'sword',
      'askPrice': 14300,
      'sellPrice': 6300,
      'description': 'なし',
      'attackNumber': 11,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 700
    },
    {
      'id': 0,
      'name': '剛剣マンジカブラ +1',
      'itemType': 'sword',
      'askPrice': 15700,
      'sellPrice': 7700,
      'description': 'なし',
      'attackNumber': 13,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 700
    },
    {
      'id': 0,
      'name': '剛剣マンジカブラ +2',
      'itemType': 'sword',
      'askPrice': 16400,
      'sellPrice': 8400,
      'description': 'なし',
      'attackNumber': 14,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 700
    },
    {
      'id': 0,
      'name': '剛剣マンジカブラ +3',
      'itemType': 'sword',
      'askPrice': 17100,
      'sellPrice': 9100,
      'description': 'なし',
      'attackNumber': 15,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': true,
      'addedPrice': 700
    },
    {
      'id': 0,
      'name': '火迅風魔刀 -1',
      'itemType': 'sword',
      'askPrice': 28750,
      'sellPrice': 11250,
      'description': 'カタナを+99を鍛冶屋に預けると取得',
      'attackNumber': 29,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 1250
    },
    {
      'id': 0,
      'name': '火迅風魔刀 +1',
      'itemType': 'sword',
      'askPrice': 31250,
      'sellPrice': 13750,
      'description': 'カタナを+99を鍛冶屋に預けると取得',
      'attackNumber': 31,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 1250
    },
    {
      'id': 0,
      'name': '火迅風魔刀 +2',
      'itemType': 'sword',
      'askPrice': 32500,
      'sellPrice': 15000,
      'description': 'カタナを+99を鍛冶屋に預けると取得',
      'attackNumber': 32,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 1250
    },
    {
      'id': 0,
      'name': '火迅風魔刀 +3',
      'itemType': 'sword',
      'askPrice': 33750,
      'sellPrice': 16250,
      'description': 'カタナを+99を鍛冶屋に預けると取得',
      'attackNumber': 33,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 1250
    },
    {
      'id': 0,
      'name': '秘剣カブラステギ -1',
      'itemType': 'sword',
      'askPrice': 38250,
      'sellPrice': 15750,
      'description': '剛剣マンジカブラを+99を鍛冶屋に預けると取得',
      'attackNumber': 49,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 1750
    },
    {
      'id': 0,
      'name': '秘剣カブラステギ +1',
      'itemType': 'sword',
      'askPrice': 41750,
      'sellPrice': 19250,
      'description': '剛剣マンジカブラを+99を鍛冶屋に預けると取得',
      'attackNumber': 51,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 1750
    },
    {
      'id': 0,
      'name': '秘剣カブラステギ +2',
      'itemType': 'sword',
      'askPrice': 43500,
      'sellPrice': 21000,
      'description': '剛剣マンジカブラを+99を鍛冶屋に預けると取得',
      'attackNumber': 52,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 1750
    },
    {
      'id': 0,
      'name': '秘剣カブラステギ +3',
      'itemType': 'sword',
      'askPrice': 45250,
      'sellPrice': 22750,
      'description': '剛剣マンジカブラを+99を鍛冶屋に預けると取得',
      'attackNumber': 53,
      'defenseNumber': null,
      '_dungeonTableMountain': false,
      '_dungeonKakejikuUra': false,
      '_dungeonSyokujin': false,
      '_dungeonFei': false,
      'addedPrice': 1750
    }
];
